# Processing Tests

Experimentation with Pandas and PyTorch to read in CSV files and output chunked time series.

This code is not professional-grade, but is provided to the curious user as a loose reference with no warranties.

In [26]:
import csv
import pandas as pd
import torch

In [2]:
file_path = '/Users/ashtoncole/Downloads/GNN_READY/MAX_0051/combined_data.csv'
df = pd.read_csv(file_path)
df

,athlete_bool,track_id,mask,frame,wx,wy,vx,vy,sx,sy,bw,bh,conf,wx_m,wy_m,vx_m,vy_m,scale_factor
0,1,track_1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,track_1,0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,track_1,0,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,track_1,0,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,track_1,0,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,1,track_5,0,330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
846,1,track_5,0,332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
847,1,track_5,0,334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
848,1,track_5,0,336,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
849,1,track_5,0,338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df['wx']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
845    0.0
846    0.0
847    0.0
848    0.0
849    0.0
Name: wx, Length: 850, dtype: float64

In [4]:
df.loc[0]

athlete_bool          1
track_id        track_1
mask                  0
frame                 0
wx                  0.0
wy                  0.0
vx                  0.0
vy                  0.0
sx                  0.0
sy                  0.0
bw                  0.0
bh                  0.0
conf                0.0
wx_m                0.0
wy_m                0.0
vx_m                0.0
vy_m                0.0
scale_factor        0.0
Name: 0, dtype: object

In [11]:
# Access single runner
runner_data = df[df['track_id'] == 'track_1']
runner_data

,athlete_bool,track_id,mask,frame,wx,wy,vx,vy,sx,sy,bw,bh,conf,wx_m,wy_m,vx_m,vy_m,scale_factor
0,1,track_1,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,track_1,0,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,1,track_1,0,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,1,track_1,0,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,1,track_1,0,8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,1,track_1,1,330,243.135284,1444.729736,-962.411743,173.952881,242.153137,1443.784546,206.839233,144.798218,0.720176,3.253703,19.333771,-12.879259,2.327885,0.013382
166,1,track_1,1,332,167.886093,1465.386475,-980.277832,191.476440,166.918396,1464.505615,252.470581,146.258667,0.701184,2.240708,19.557925,-13.083375,2.555559,0.013347
167,1,track_1,1,334,108.101967,1480.279053,-983.532288,198.411255,107.095879,1479.406860,214.191757,157.789551,0.773289,1.438937,19.703879,-13.091721,2.641037,0.013311
168,1,track_1,1,336,59.450249,1493.942017,-961.794312,206.763306,58.424061,1493.055298,116.848122,149.170776,0.701484,0.789217,19.832447,-12.768055,2.744834,0.013275
169,1,track_1,1,338,33.192745,1502.517578,-914.149780,208.127075,32.189739,1501.629028,64.379478,136.987671,0.589315,0.425323,19.252869,-11.713677,2.666886,0.012814

In [12]:
# num_frames
num_frames = len(runner_data)
num_frames

170

In [21]:
# num_particles
num_runners = int(len(df) / num_frames)
num_runners

5

In [22]:
# Check consistency
num_runners * num_frames

850

In [23]:
len(df)

850

In [27]:
# Create tensor
dim_state_reduced = 2 + 2 + 2
data = torch.zeros((num_frames, num_runners, dim_state_reduced), dtype=torch.float32)
data

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        ...,

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [24]:
# Looping across runners
for i in range(num_runners):
    runner_data = df[df['track_id'] == f'track_{i + 1}']
    print(runner_data)
    print('\n\n\n\n\n')

     athlete_bool track_id  mask  frame          wx           wy          vx  \
0               1  track_1     0      0    0.000000     0.000000    0.000000
1               1  track_1     0      2    0.000000     0.000000    0.000000
2               1  track_1     0      4    0.000000     0.000000    0.000000
3               1  track_1     0      6    0.000000     0.000000    0.000000
4               1  track_1     0      8    0.000000     0.000000    0.000000
..            ...      ...   ...    ...         ...          ...         ...
165             1  track_1     1    330  243.135284  1444.729736 -962.411743
166             1  track_1     1    332  167.886093  1465.386475 -980.277832
167             1  track_1     1    334  108.101967  1480.279053 -983.532288
168             1  track_1     1    336   59.450249  1493.942017 -961.794312
169             1  track_1     1    338   33.192745  1502.517578 -914.149780

             vy          sx           sy          bw          bh      conf  \
0      0.000000    0.000000     0.000000    0.000000    0.000000  0.000000
1      0.000000    0.000000     0.000000    0.000000    0.000000  0.000000
2      0.000000    0.000000     0.000000    0.000000    0.000000  0.000000
3      0.000000    0.000000     0.000000    0.000000    0.000000  0.000000
4      0.000000    0.000000     0.000000    0.000000    0.000000  0.000000
..          ...         ...          ...         ...         ...       ...
165  173.952881  242.153137  1443.784546  206.839233  144.798218  0.720176
166  191.476440  166.918396  1464.505615  252.470581  146.258667  0.701184
167  198.411255  107.095879  1479.406860  214.191757  157.789551  0.773289
168  206.763306   58.424061  1493.055298  116.848122  149.170776  0.701484
169  208.127075   32.189739  1501.629028   64.379478  136.987671  0.589315

         wx_m       wy_m       vx_m      vy_m  scale_factor
0    0.000000   0.000000   0.000000  0.000000      0.000000
1    0.000000   0.000000   0.000000  0.000000      0.000000
2    0.000000   0.000000   0.000000  0.000000      0.000000
3    0.000000   0.000000   0.000000  0.000000      0.000000
4    0.000000   0.000000   0.000000  0.000000      0.000000
..        ...        ...        ...       ...           ...
165  3.253703  19.333771 -12.879259  2.327885      0.013382
166  2.240708  19.557925 -13.083375  2.555559      0.013347
167  1.438937  19.703879 -13.091721  2.641037      0.013311
168  0.789217  19.832447 -12.768055  2.744834      0.013275
169  0.425323  19.252869 -11.713677  2.666886      0.012814

[170 rows x 18 columns]






     athlete_bool track_id  mask  frame   wx   wy   vx   vy   sx   sy   bw  \
170             1  track_2     0      0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
171             1  track_2     0      2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
172             1  track_2     0      4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
173             1  track_2     0      6  0.0  0.0  0.0  0.0  0.0  0.0  0.0
174             1  track_2     0      8  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..            ...      ...   ...    ...  ...  ...  ...  ...  ...  ...  ...
335             1  track_2     0    330  0.0  0.0  0.0  0.0  0.0  0.0  0.0
336             1  track_2     0    332  0.0  0.0  0.0  0.0  0.0  0.0  0.0
337             1  track_2     0    334  0.0  0.0  0.0  0.0  0.0  0.0  0.0
338             1  track_2     0    336  0.0  0.0  0.0  0.0  0.0  0.0  0.0
339             1  track_2     0    338  0.0  0.0  0.0  0.0  0.0  0.0  0.0

      bh  conf  wx_m  wy_m  vx_m  vy_m  scale_factor
170  0.0   0.0   0.0   0.0   0.0   0.0           0.0
171  0.0   0.0   0.0   0.0   0.0   0.0           0.0
172  0.0   0.0   0.0   0.0   0.0   0.0           0.0
173  0.0   0.0   0.0   0.0   0.0   0.0           0.0
174  0.0   0.0   0.0   0.0   0.0   0.0           0.0
..   ...   ...   ...   ...   ...   ...           ...
335  0.0   0.0   0.0   0.0   0.0   0.0           0.0
336  0.0   0.0   0.0   0.0   0.0   0.0           0.0
337  0.0   0.0   0.0   0.0   0.0   0.0           0.0
338  0.0   0.0   0.0   0.0   0.0   0.0           0.0
339  0.0   0.0   0.0   0.0   0.0   0.0           0.0

[170 rows x 18 columns]






     athlete_bool track_id  mask  frame   wx   wy   vx   vy   sx   sy   bw  \
340             1  track_3     0      0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
341             1  track_3     0      2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
342             1  track_3     0      4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
343             1  track_3     0      6  0.0  0.0  0.0  0.0  0.0  0.0  0.0
344             1  track_3     0      8  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..            ...      ...   ...    ...  ...  ...  ...  ...  ...  ...  ...
505             1  track_3     0    330  0.0  0.0  0.0  0.0  0.0  0.0  0.0
506             1  track_3     0    332  0.0  0.0  0.0  0.0  0.0  0.0  0.0
507             1  track_3     0    334  0.0  0.0  0.0  0.0  0.0  0.0  0.0
508             1  track_3     0    336  0.0  0.0  0.0  0.0  0.0  0.0  0.0
509             1  track_3     0    338  0.0  0.0  0.0  0.0  0.0  0.0  0.0

      bh  conf  wx_m  wy_m  vx_m  vy_m  scale_factor
340  0.0   0.0   0.0   0.0   0.0   0.0           0.0
341  0.0   0.0   0.0   0.0   0.0   0.0           0.0
342  0.0   0.0   0.0   0.0   0.0   0.0           0.0
343  0.0   0.0   0.0   0.0   0.0   0.0           0.0
344  0.0   0.0   0.0   0.0   0.0   0.0           0.0
..   ...   ...   ...   ...   ...   ...           ...
505  0.0   0.0   0.0   0.0   0.0   0.0           0.0
506  0.0   0.0   0.0   0.0   0.0   0.0           0.0
507  0.0   0.0   0.0   0.0   0.0   0.0           0.0
508  0.0   0.0   0.0   0.0   0.0   0.0           0.0
509  0.0   0.0   0.0   0.0   0.0   0.0           0.0

[170 rows x 18 columns]






     athlete_bool track_id  mask  frame   wx   wy   vx   vy   sx   sy   bw  \
510             1  track_4     0      0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
511             1  track_4     0      2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
512             1  track_4     0      4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
513             1  track_4     0      6  0.0  0.0  0.0  0.0  0.0  0.0  0.0
514             1  track_4     0      8  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..            ...      ...   ...    ...  ...  ...  ...  ...  ...  ...  ...
675             1  track_4     0    330  0.0  0.0  0.0  0.0  0.0  0.0  0.0
676             1  track_4     0    332  0.0  0.0  0.0  0.0  0.0  0.0  0.0
677             1  track_4     0    334  0.0  0.0  0.0  0.0  0.0  0.0  0.0
678             1  track_4     0    336  0.0  0.0  0.0  0.0  0.0  0.0  0.0
679             1  track_4     0    338  0.0  0.0  0.0  0.0  0.0  0.0  0.0

      bh  conf  wx_m  wy_m  vx_m  vy_m  scale_factor
510  0.0   0.0   0.0   0.0   0.0   0.0           0.0
511  0.0   0.0   0.0   0.0   0.0   0.0           0.0
512  0.0   0.0   0.0   0.0   0.0   0.0           0.0
513  0.0   0.0   0.0   0.0   0.0   0.0           0.0
514  0.0   0.0   0.0   0.0   0.0   0.0           0.0
..   ...   ...   ...   ...   ...   ...           ...
675  0.0   0.0   0.0   0.0   0.0   0.0           0.0
676  0.0   0.0   0.0   0.0   0.0   0.0           0.0
677  0.0   0.0   0.0   0.0   0.0   0.0           0.0
678  0.0   0.0   0.0   0.0   0.0   0.0           0.0
679  0.0   0.0   0.0   0.0   0.0   0.0           0.0

[170 rows x 18 columns]






     athlete_bool track_id  mask  frame   wx   wy   vx   vy   sx   sy   bw  \
680             1  track_5     0      0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
681             1  track_5     0      2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
682             1  track_5     0      4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
683             1  track_5     0      6  0.0  0.0  0.0  0.0  0.0  0.0  0.0
684             1  track_5     0      8  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..            ...      ...   ...    ...  ...  ...  ...  ...  ...  ...  ...
845             1  track_5     0    330  0.0  0.0  0.0  0.0  0.0  0.0  0.0
846             1  track_5     0    332  0.0  0.0  0.0  0.0  0.0  0.0  0.0
847             1  track_5     0    334  0.0  0.0  0.0  0.0  0.0  0.0  0.0
848             1  track_5     0    336  0.0  0.0  0.0  0.0  0.0  0.0  0.0
849             1  track_5     0    338  0.0  0.0  0.0  0.0  0.0  0.0  0.0

      bh  conf  wx_m  wy_m  vx_m  vy_m  scale_factor
680  0.0   0.0   0.0   0.0   0.0   0.0           0.0
681  0.0   0.0   0.0   0.0   0.0   0.0           0.0
682  0.0   0.0   0.0   0.0   0.0   0.0           0.0
683  0.0   0.0   0.0   0.0   0.0   0.0           0.0
684  0.0   0.0   0.0   0.0   0.0   0.0           0.0
..   ...   ...   ...   ...   ...   ...           ...
845  0.0   0.0   0.0   0.0   0.0   0.0           0.0
846  0.0   0.0   0.0   0.0   0.0   0.0           0.0
847  0.0   0.0   0.0   0.0   0.0   0.0           0.0
848  0.0   0.0   0.0   0.0   0.0   0.0           0.0
849  0.0   0.0   0.0   0.0   0.0   0.0           0.0

[170 rows x 18 columns]

In [32]:
# Access data for a single runner
i = 0 # First runner
df.loc[df['track_id'] == f'track_{i + 1}', ['wx', 'wy']] # x, y

             wx           wy
0      0.000000     0.000000
1      0.000000     0.000000
2      0.000000     0.000000
3      0.000000     0.000000
4      0.000000     0.000000
..          ...          ...
165  243.135284  1444.729736
166  167.886093  1465.386475
167  108.101967  1480.279053
168   59.450249  1493.942017
169   33.192745  1502.517578

[170 rows x 2 columns]

In [41]:
torch.from_numpy(df.loc[df['track_id'] == f'track_{i + 1}', ['bw', 'bh']].iloc[-5:].to_numpy())

tensor([[206.8392, 144.7982],
        [252.4706, 146.2587],
        [214.1918, 157.7896],
        [116.8481, 149.1708],
        [ 64.3795, 136.9877]], dtype=torch.float64)

In [44]:
res = torch.max(torch.from_numpy(df.loc[df['track_id'] == f'track_{i + 1}', ['bw', 'bh']].iloc[-5:].to_numpy()), dim=-1)
res

torch.return_types.max(
values=tensor([206.8392, 252.4706, 214.1918, 149.1708, 136.9877], dtype=torch.float64),
indices=tensor([0, 0, 0, 1, 1]))

In [45]:
res[0]

tensor([206.8392, 252.4706, 214.1918, 149.1708, 136.9877], dtype=torch.float64)

In [57]:
# Assign data to single runner
i = 0 # First runner
runner_data = df[df['track_id'] == f'track_{i + 1}']
data[:, i, 0:2] = torch.from_numpy(runner_data[['wx', 'wy']].to_numpy()) # x, y
data[:, i, 2:4] = torch.from_numpy(runner_data[['vx', 'vy']].to_numpy()) # vx, vy
data[:, i, 4] = torch.max(torch.from_numpy(runner_data[['bw', 'bh']].to_numpy()), dim=-1)[0] # max(bw, bh)
data[:, i, 5] = torch.from_numpy(runner_data['conf'].to_numpy()) # conf
data[:, i, :]

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        ...,
        [ 1.0810e+02,  1.4803e+03, -9.8353e+02,  1.9841e+02,  2.1419e+02,
          7.7329e-01],
        [ 5.9450e+01,  1.4939e+03, -9.6179e+02,  2.0676e+02,  1.4917e+02,
          7.0148e-01],
        [ 3.3193e+01,  1.5025e+03, -9.1415e+02,  2.0813e+02,  1.3699e+02,
          5.8931e-01]])

In [68]:
# Convert mask to bool
i = 0
df.loc[df['track_id'] == f'track_{i + 1}', 'mask'] == 1

0      False
1      False
2      False
3      False
4      False
       ...
165     True
166     True
167     True
168     True
169     True
Name: mask, Length: 170, dtype: bool

In [75]:
# Combined mask
i = 0
mask = (df.loc[df['track_id'] == f'track_{i + 1}', 'mask'] == 1).to_numpy()
for i in range(num_runners):
    runner_mask = (df.loc[df['track_id'] == f'track_{i + 1}', 'mask'] == 1).to_numpy()
    print(f'runner {i + 1}:')
    print(runner_mask)
    mask = mask & runner_mask
mask

runner 1:
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
runner 2:
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False  True  True False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
runner 3:
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
runner 4:
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False]
runner 5:
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [94]:
# Chunking
# Create new data frame to hold which runners are visible at a given moment
masks = df.pivot(index='frame', columns='track_id', values='mask')
runner_columns = [f'track_{i + 1}' for i in range(num_runners)]
masks['current_state'] = masks[runner_columns].apply(tuple, axis=1)
masks

track_id  track_1  track_2  track_3  track_4  track_5    current_state
frame
0               0        0        0        0        0  (0, 0, 0, 0, 0)
2               0        0        0        0        0  (0, 0, 0, 0, 0)
4               0        0        0        0        0  (0, 0, 0, 0, 0)
6               0        0        0        0        0  (0, 0, 0, 0, 0)
8               0        0        0        0        0  (0, 0, 0, 0, 0)
...           ...      ...      ...      ...      ...              ...
330             1        0        0        0        0  (1, 0, 0, 0, 0)
332             1        0        0        0        0  (1, 0, 0, 0, 0)
334             1        0        0        0        0  (1, 0, 0, 0, 0)
336             1        0        0        0        0  (1, 0, 0, 0, 0)
338             1        0        0        0        0  (1, 0, 0, 0, 0)

[170 rows x 6 columns]

In [112]:
# Compute chunks
masks['state_changed'] = masks['current_state'] != masks['current_state'].shift(1)
masks['chunk_id'] = masks['state_changed'].cumsum()
# Count number of runners
masks['num_runners'] = masks[runner_columns].sum(axis=1)
masks

track_id,track_1,track_2,track_3,track_4,track_5,current_state,state_changed,chunk_id,num_runners
frame,,,,,,,,,
0,0,0,0,0,0,"(0, 0, 0, 0, 0)",True,1,0
2,0,0,0,0,0,"(0, 0, 0, 0, 0)",False,1,0
4,0,0,0,0,0,"(0, 0, 0, 0, 0)",False,1,0
6,0,0,0,0,0,"(0, 0, 0, 0, 0)",False,1,0
8,0,0,0,0,0,"(0, 0, 0, 0, 0)",False,1,0
...,...,...,...,...,...,...,...,...,...
330,1,0,0,0,0,"(1, 0, 0, 0, 0)",False,14,1
332,1,0,0,0,0,"(1, 0, 0, 0, 0)",False,14,1
334,1,0,0,0,0,"(1, 0, 0, 0, 0)",False,14,1
336,1,0,0,0,0,"(1, 0, 0, 0, 0)",False,14,1
338,1,0,0,0,0,"(1, 0, 0, 0, 0)",False,14,1

In [149]:
min_chunk_length = 0
min_runners = 2
# Iterate through each chunk
for chunk_id, chunk_data in masks.groupby('chunk_id'):
    print(f'chunk id: {chunk_id} -----------------------')
    len_chunk = len(chunk_data)
    print(f'length of chunk: {len_chunk}')
    # Exclude if too short
    if len_chunk < min_chunk_length:
        print('Too short, excluding')
        continue
    runners_state = chunk_data[runner_columns].iloc[0] # Which runners are in
    print(f'runner state: {runners_state}')
    runners_present = [f'track_{j + 1}' for j in range(num_runners) if runners_state[f'track_{j + 1}'] == 1]
    print(f'present runners: {runners_present}')
    num_runners_chunk = chunk_data['num_runners'].iloc[0]
    print(f'number of runners: {num_runners_chunk}')
    # Exclude if no runners
    if num_runners_chunk < min_runners:
        print('Too short, excluding')
        continue
    frames_in_chunk = chunk_data.index
    print(f'associated video frames {frames_in_chunk}')
        
    # Create 3D tensor
    dim_state_reduced = 2 + 2 + 2 # (x, y, vx, vy, max(bw, bh), conf)
    states_chunk = torch.zeros((len_chunk, num_runners_chunk, dim_state_reduced), dtype=torch.float32)
    
    # Loop across runners to fill in data
    for i in range(num_runners_chunk):
        runner_data = df[(df['track_id'] == runners_present[i]) & df['frame'].isin(frames_in_chunk)]
        states_chunk[:, i, 0:2] = torch.from_numpy(runner_data[['wx', 'wy']].to_numpy()) # x, y
        states_chunk[:, i, 2:4] = torch.from_numpy(runner_data[['vx', 'vy']].to_numpy()) # vx, vy
        states_chunk[:, i, 4] = torch.max(torch.from_numpy(runner_data[['bw', 'bh']].to_numpy()), dim=-1)[0] # max(bw, bh)
        states_chunk[:, i, 5] = torch.from_numpy(runner_data['conf'].to_numpy()) # conf
    print(states_chunk)

chunk id: 1 -----------------------
length of chunk: 87
runner state: track_id
track_1    0
track_2    0
track_3    0
track_4    0
track_5    0
Name: 0, dtype: int64
present runners: []
number of runners: 0
Too short, excluding
chunk id: 2 -----------------------
length of chunk: 2
runner state: track_id
track_1    0
track_2    1
track_3    0
track_4    0
track_5    0
Name: 174, dtype: int64
present runners: ['track_2']
number of runners: 1
associated video frames Index([174, 176], dtype='int64', name='frame')
tensor([[[ 3.6490e+03,  1.2476e+03,  0.0000e+00,  0.0000e+00,  1.6582e+02,
           7.0854e-01]],

        [[ 3.5870e+03,  1.2602e+03, -9.3020e+02,  1.8865e+02,  2.0312e+02,
           8.0708e-01]]])
chunk id: 3 -----------------------
length of chunk: 1
runner state: track_id
track_1    0
track_2    0
track_3    0
track_4    0
track_5    0
Name: 178, dtype: int64
present runners: []
number of runners: 0
Too short, excluding
chunk id: 4 -----------------------
length of chunk: 1
runner state: track_id
track_1    0
track_2    1
track_3    0
track_4    0
track_5    0
Name: 180, dtype: int64
present runners: ['track_2']
number of runners: 1
associated video frames Index([180], dtype='int64', name='frame')
tensor([[[ 3.4517e+03,  1.2433e+03, -1.0150e+03, -1.2679e+02,  2.0334e+02,
           7.3916e-01]]])
chunk id: 5 -----------------------
length of chunk: 4
runner state: track_id
track_1    0
track_2    1
track_3    1
track_4    0
track_5    0
Name: 182, dtype: int64
present runners: ['track_2', 'track_3']
number of runners: 2
associated video frames Index([182, 184, 186, 188], dtype='int64', name='frame')
tensor([[[ 3.3860e+03,  1.1632e+03, -9.8463e+02, -1.2012e+03,  1.4194e+02,
           5.3164e-01],
         [ 3.7605e+03,  1.1168e+03,  0.0000e+00,  0.0000e+00,  1.4333e+02,
           4.8540e-01]],

        [[ 3.3126e+03,  1.1665e+03, -1.1015e+03,  4.9459e+01,  1.6172e+02,
           7.5425e-01],
         [ 3.6988e+03,  1.1100e+03, -9.2578e+02, -1.0077e+02,  1.9986e+02,
           6.3397e-01]],

        [[ 3.2456e+03,  1.1798e+03, -1.0040e+03,  1.9984e+02,  2.1458e+02,
           7.4923e-01],
         [ 3.6439e+03,  1.0743e+03, -8.2409e+02, -5.3578e+02,  1.9185e+02,
           5.7386e-01]],

        [[ 3.1779e+03,  1.1744e+03, -1.0162e+03, -8.2072e+01,  2.2566e+02,
           7.4398e-01],
         [ 3.5697e+03,  1.0690e+03, -1.1131e+03, -7.9585e+01,  1.8502e+02,
           7.6685e-01]]])
chunk id: 6 -----------------------
length of chunk: 11
runner state: track_id
track_1    0
track_2    1
track_3    1
track_4    1
track_5    0
Name: 190, dtype: int64
present runners: ['track_2', 'track_3', 'track_4']
number of runners: 3
associated video frames Index([190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210], dtype='int64', name='frame')
tensor([[[ 3.1053e+03,  1.1430e+03, -1.0896e+03, -4.7095e+02,  1.7661e+02,
           7.3332e-01],
         [ 3.4896e+03,  1.0651e+03, -1.2013e+03, -5.8857e+01,  1.7513e+02,
           7.5362e-01],
         [ 3.4661e+03,  9.1169e+02,  0.0000e+00,  0.0000e+00,  1.7816e+02,
           7.2766e-01]],

        [[ 3.0307e+03,  1.1218e+03, -1.1178e+03, -3.1703e+02,  1.6542e+02,
           7.5505e-01],
         [ 3.4188e+03,  1.0589e+03, -1.0615e+03, -9.2796e+01,  1.9637e+02,
           7.7320e-01],
         [ 3.4156e+03,  8.9296e+02, -7.5827e+02, -2.8083e+02,  2.0257e+02,
           7.4960e-01]],

        [[ 2.9725e+03,  1.1327e+03, -8.7351e+02,  1.6323e+02,  1.9032e+02,
           7.4886e-01],
         [ 3.3516e+03,  1.0401e+03, -1.0077e+03, -2.8253e+02,  2.0065e+02,
           8.0223e-01],
         [ 3.3512e+03,  8.7202e+02, -9.6590e+02, -3.1420e+02,  1.7347e+02,
           7.5658e-01]],

        [[ 2.9161e+03,  1.1150e+03, -8.4605e+02, -2.6632e+02,  1.7857e+02,
           5.9120e-01],
         [ 3.2863e+03,  1.0134e+03, -9.8046e+02, -4.0075e+02,  1.6496e+02,
           7.5106e-01],
         [ 3.2849e+03,  8.5195e+02, -9.9401e+02, -3.0099e+02,  1.6485e+02,
           3.8183e-01]],

        [[ 2.8422e+03,  1.1130e+03, -1.1088e+03, -2.9899e+01,  1.9059e+02,
           7.5690e-01],
         [ 3.2085e+03,  9.9295e+02, -1.1668e+03, -3.0611e+02,  1.5482e+02,
           7.4327e-01],
         [ 3.2126e+03,  8.3229e+02, -1.0844e+03, -2.9489e+02,  1.5991e+02,
           7.6442e-01]],

        [[ 2.7668e+03,  1.0696e+03, -1.1314e+03, -6.5083e+02,  1.5692e+02,
           7.3665e-01],
         [ 3.1389e+03,  9.8318e+02, -1.0437e+03, -1.4652e+02,  1.7460e+02,
           7.3501e-01],
         [ 3.1603e+03,  8.2820e+02, -7.8483e+02, -6.1425e+01,  1.8052e+02,
           7.6012e-01]],

        [[ 2.7079e+03,  1.0599e+03, -8.8351e+02, -1.4579e+02,  1.5158e+02,
           7.1597e-01],
         [ 3.0733e+03,  9.7228e+02, -9.8321e+02, -1.6352e+02,  1.9481e+02,
           7.6890e-01],
         [ 3.0814e+03,  8.2054e+02, -1.1841e+03, -1.1494e+02,  1.6880e+02,
           7.0743e-01]],

        [[ 2.6416e+03,  1.0706e+03, -9.9324e+02,  1.6150e+02,  1.8034e+02,
           7.5773e-01],
         [ 3.0059e+03,  9.6052e+02, -1.0118e+03, -1.7645e+02,  1.6379e+02,
           7.4788e-01],
         [ 3.0127e+03,  8.0776e+02, -1.0303e+03, -1.9156e+02,  1.5628e+02,
           7.2759e-01]],

        [[ 2.5714e+03,  1.0775e+03, -1.0103e+03, -1.5953e+02,  2.0963e+02,
           7.5787e-01],
         [ 2.9306e+03,  9.5589e+02, -1.1295e+03, -6.9431e+01,  1.5381e+02,
           7.3373e-01],
         [ 2.9494e+03,  8.1193e+02, -9.4891e+02,  6.2496e+01,  1.8130e+02,
           7.1848e-01]],

        [[ 2.4999e+03,  1.0505e+03, -1.0192e+03, -1.9662e+02,  1.6438e+02,
           7.0164e-01],
         [ 2.8702e+03,  9.5509e+02, -9.0666e+02, -1.1899e+01,  1.5034e+02,
           7.4182e-01],
         [ 2.8882e+03,  7.9687e+02, -9.1859e+02, -2.2585e+02,  1.7951e+02,
           7.3066e-01]],

        [[ 2.4228e+03,  1.0357e+03, -1.0288e+03, -2.0763e+02,  1.5770e+02,
           7.5452e-01],
         [ 2.8047e+03,  9.4435e+02, -9.8154e+02, -1.6122e+02,  1.6544e+02,
           7.5790e-01],
         [ 2.8184e+03,  7.8780e+02, -1.0464e+03, -1.3604e+02,  1.9558e+02,
           7.9167e-01]]])
chunk id: 7 -----------------------
length of chunk: 2
runner state: track_id
track_1    0
track_2    1
track_3    1
track_4    1
track_5    1
Name: 212, dtype: int64
present runners: ['track_2', 'track_3', 'track_4', 'track_5']
number of runners: 4
associated video frames Index([212, 214], dtype='int64', name='frame')
tensor([[[ 2.3679e+03,  1.0420e+03, -1.0181e+03, -1.2117e+02,  1.6936e+02,
           7.0826e-01],
         [ 2.7367e+03,  9.2789e+02, -1.0238e+03, -1.8887e+02,  1.4600e+02,
           7.6061e-01],
         [ 2.7515e+03,  7.7598e+02, -1.0033e+03, -1.7733e+02,  1.6216e+02,
           7.5573e-01],
         [ 2.6041e+03,  6.3387e+02,  0.0000e+00,  0.0000e+00,  1.9399e+02,
           5.0392e-01]],

        [[ 2.3033e+03,  1.0446e+03, -1.0093e+03, -1.2191e+02,  1.9749e+02,
           7.3205e-01],
         [ 2.6593e+03,  9.0705e+02, -1.0395e+03, -2.0299e+02,  1.3301e+02,
           7.5216e-01],
         [ 2.6866e+03,  7.7043e+02, -9.7413e+02, -8.3221e+01,  1.6369e+02,
           7.5619e-01],
         [ 2.5438e+03,  6.3023e+02, -9.0447e+02, -5.4645e+01,  1.7905e+02,
           6.1660e-01]]])
chunk id: 8 -----------------------
length of chunk: 1
runner state: track_id
track_1    0
track_2    1
track_3    1
track_4    1
track_5    0
Name: 216, dtype: int64
present runners: ['track_2', 'track_3', 'track_4']
number of runners: 3
associated video frames Index([216], dtype='int64', name='frame')
tensor([[[ 2.2343e+03,  1.0450e+03, -1.0114e+03, -1.3483e+02,  1.9050e+02,
           7.8493e-01],
         [ 2.5997e+03,  9.0225e+02, -1.0441e+03, -1.7207e+02,  1.4168e+02,
           7.5552e-01],
         [ 2.6306e+03,  7.7129e+02, -8.3984e+02,  1.2894e+01,  1.7989e+02,
           7.3176e-01]]])
chunk id: 9 -----------------------
length of chunk: 3
runner state: track_id
track_1    0
track_2    1
track_3    1
track_4    1
track_5    1
Name: 218, dtype: int64
present runners: ['track_2', 'track_3', 'track_4', 'track_5']
number of runners: 4
associated video frames Index([218, 220, 222], dtype='int64', name='frame')
tensor([[[ 2.1676e+03,  1.0186e+03, -1.0103e+03, -1.5576e+02,  1.6054e+02,
           7.5505e-01],
         [ 2.5294e+03,  9.0373e+02, -1.0403e+03, -1.6529e+02,  1.7850e+02,
           7.5007e-01],
         [ 2.5610e+03,  7.6847e+02, -1.0436e+03, -4.2288e+01,  1.9849e+02,
           7.2493e-01],
         [ 2.4110e+03,  6.3112e+02, -9.9571e+02,  6.6824e+00,  1.8141e+02,
           7.6439e-01]],

        [[ 2.1017e+03,  9.9886e+02, -1.0036e+03, -1.4410e+02,  1.4666e+02,
           6.9767e-01],
         [ 2.4575e+03,  9.0252e+02, -1.0320e+03, -1.6258e+02,  1.6489e+02,
           7.5038e-01],
         [ 2.4926e+03,  7.6440e+02, -9.7350e+02, -1.4729e+02,  1.7093e+02,
           7.7152e-01],
         [ 2.3511e+03,  6.3753e+02, -8.9862e+02,  9.6083e+01,  2.1819e+02,
           7.7023e-01]],

        [[ 2.0389e+03,  1.0244e+03, -9.9184e+02, -9.7408e+01,  1.7911e+02,
           7.9322e-01],
         [ 2.3868e+03,  8.9963e+02, -1.0320e+03, -1.5928e+02,  1.4031e+02,
           7.2787e-01],
         [ 2.4162e+03,  7.6084e+02, -9.9941e+02, -1.3212e+02,  1.7574e+02,
           7.4492e-01],
         [ 2.2843e+03,  6.3669e+02, -1.0017e+03, -1.2641e+01,  2.1415e+02,
           6.3882e-01]]])
chunk id: 10 -----------------------
length of chunk: 22
runner state: track_id
track_1    1
track_2    1
track_3    1
track_4    1
track_5    1
Name: 224, dtype: int64
present runners: ['track_1', 'track_2', 'track_3', 'track_4', 'track_5']
number of runners: 5
associated video frames Index([224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250,
       252, 254, 256, 258, 260, 262, 264, 266],
      dtype='int64', name='frame')
tensor([[[ 3.6877e+03,  1.4340e+03,  0.0000e+00,  0.0000e+00,  1.6443e+02,
           7.3931e-01],
         [ 1.9770e+03,  1.0296e+03, -9.9555e+02, -1.0315e+02,  2.0409e+02,
           7.7634e-01],
         [ 2.3204e+03,  8.9621e+02, -1.0312e+03, -1.4386e+02,  1.5266e+02,
           7.6260e-01],
         [ 2.3622e+03,  7.6168e+02, -9.8896e+02, -1.1034e+02,  1.7577e+02,
           7.6109e-01],
         [ 2.2200e+03,  6.2679e+02, -9.6446e+02, -1.4850e+02,  1.8914e+02,
           5.4306e-01]],

        [[ 3.6291e+03,  1.4286e+03, -8.7881e+02, -8.2282e+01,  1.9857e+02,
           7.8540e-01],
         [ 1.9073e+03,  1.0145e+03, -1.0088e+03, -1.0045e+02,  1.7392e+02,
           7.4631e-01],
         [ 2.2560e+03,  8.9590e+02, -1.0302e+03, -1.1745e+02,  1.7253e+02,
           7.5572e-01],
         [ 2.3067e+03,  7.5353e+02, -9.7826e+02, -9.8426e+01,  1.8623e+02,
           7.8256e-01],
         [ 2.1664e+03,  6.2266e+02, -8.0438e+02, -6.1895e+01,  1.9157e+02,
           4.3064e-01]],

        [[ 3.5623e+03,  1.4277e+03, -1.0025e+03, -1.3017e+01,  2.3232e+02,
           7.9241e-01],
         [ 1.8345e+03,  1.0068e+03, -1.0077e+03, -1.0621e+02,  1.5013e+02,
           7.5915e-01],
         [ 2.1899e+03,  8.8817e+02, -1.0185e+03, -1.0478e+02,  1.4269e+02,
           7.1283e-01],
         [ 2.2383e+03,  7.4612e+02, -9.7432e+02, -8.6168e+01,  1.6589e+02,
           7.3701e-01],
         [ 2.1056e+03,  6.2403e+02, -9.1221e+02,  2.0561e+01,  1.9082e+02,
           8.0596e-01]],

        [[ 3.4909e+03,  1.4147e+03, -1.0709e+03, -1.9439e+02,  2.3623e+02,
           7.3664e-01],
         [ 1.7698e+03,  1.0192e+03, -9.9691e+02, -5.0395e+01,  1.6782e+02,
           6.0267e-01],
         [ 2.1138e+03,  8.8221e+02, -1.0250e+03, -1.0097e+02,  1.3842e+02,
           7.5667e-01],
         [ 2.1619e+03,  7.4010e+02, -9.9840e+02, -8.8100e+01,  1.6463e+02,
           7.7122e-01],
         [ 2.0406e+03,  6.2386e+02, -9.7490e+02, -2.6111e+00,  1.9164e+02,
           7.7428e-01]],

        [[ 3.4214e+03,  1.3809e+03, -1.0424e+03, -5.0767e+02,  1.8030e+02,
           7.5315e-01],
         [ 1.7091e+03,  1.0362e+03, -9.9874e+02, -2.3636e+01,  1.9797e+02,
           7.4059e-01],
         [ 2.0506e+03,  8.8422e+02, -1.0228e+03, -8.8058e+01,  1.6307e+02,
           7.6364e-01],
         [ 2.1048e+03,  7.4385e+02, -9.7654e+02, -7.6681e+01,  1.6575e+02,
           7.4489e-01],
         [ 1.9754e+03,  6.2124e+02, -9.7758e+02, -3.9278e+01,  1.9050e+02,
           6.9139e-01]],

        [[ 3.3471e+03,  1.3491e+03, -1.1150e+03, -4.7672e+02,  1.5501e+02,
           7.4733e-01],
         [ 1.6363e+03,  1.0243e+03, -1.0054e+03, -4.6319e+01,  1.7631e+02,
           7.1800e-01],
         [ 1.9827e+03,  8.8704e+02, -1.0232e+03, -7.3475e+01,  1.8000e+02,
           7.8503e-01],
         [ 2.0486e+03,  7.5054e+02, -9.6409e+02, -5.7220e+01,  1.8581e+02,
           7.4702e-01],
         [ 1.9093e+03,  6.2058e+02, -9.9080e+02, -9.8199e+00,  1.7490e+02,
           6.1180e-01]],

        [[ 3.2774e+03,  1.3461e+03, -1.0453e+03, -4.4998e+01,  1.8647e+02,
           7.6896e-01],
         [ 1.5678e+03,  1.0155e+03, -1.0036e+03, -6.2003e+01,  1.6189e+02,
           7.1393e-01],
         [ 1.9103e+03,  8.8909e+02, -1.0203e+03, -6.6796e+01,  1.5127e+02,
           7.3451e-01],
         [ 1.9787e+03,  7.5703e+02, -9.7072e+02, -5.4898e+01,  1.8086e+02,
           7.4942e-01],
         [ 1.8510e+03,  6.2517e+02, -8.7559e+02,  6.8768e+01,  1.8169e+02,
           7.8045e-01]],

        [[ 3.2217e+03,  1.3323e+03, -8.3534e+02, -2.0693e+02,  2.1507e+02,
           7.6178e-01],
         [ 1.5030e+03,  1.0127e+03, -9.9685e+02, -3.7724e+01,  1.5091e+02,
           7.0938e-01],
         [ 1.8475e+03,  8.9148e+02, -1.0226e+03, -6.3613e+01,  1.3618e+02,
           7.4819e-01],
         [ 1.9099e+03,  7.4733e+02, -9.7824e+02, -4.9542e+01,  1.7084e+02,
           7.1295e-01],
         [ 1.7894e+03,  6.2385e+02, -9.2327e+02, -1.9788e+01,  2.0260e+02,
           7.8307e-01]],

        [[ 3.1503e+03,  1.3134e+03, -1.0711e+03, -2.8426e+02,  2.1694e+02,
           7.8906e-01],
         [ 1.4406e+03,  1.0262e+03, -9.8224e+02, -9.4895e+00,  1.7414e+02,
           7.3368e-01],
         [ 1.7839e+03,  8.9360e+02, -1.0208e+03, -5.0743e+01,  1.6284e+02,
           7.3653e-01],
         [ 1.8471e+03,  7.4810e+02, -9.7132e+02, -3.9706e+01,  1.6557e+02,
           7.4564e-01],
         [ 1.7247e+03,  6.3147e+02, -9.7126e+02,  1.1427e+02,  1.7697e+02,
           7.8069e-01]],

        [[ 3.0704e+03,  1.2965e+03, -1.1986e+03, -2.5298e+02,  1.7212e+02,
           7.3445e-01],
         [ 1.3661e+03,  1.0506e+03, -1.0018e+03,  8.5964e+00,  1.8291e+02,
           7.3830e-01],
         [ 1.7202e+03,  8.9397e+02, -1.0165e+03, -3.3924e+01,  1.8525e+02,
           7.5678e-01],
         [ 1.7920e+03,  7.4912e+02, -9.5952e+02, -2.6857e+01,  1.7355e+02,
           7.7567e-01],
         [ 1.6573e+03,  6.3028e+02, -1.0111e+03, -1.7712e+01,  1.6870e+02,
           7.4161e-01]],

        [[ 3.0006e+03,  1.2884e+03, -1.0466e+03, -1.2137e+02,  1.5615e+02,
           7.3251e-01],
         [ 1.2999e+03,  1.0436e+03, -1.0034e+03, -1.0262e+00,  1.6659e+02,
           7.2633e-01],
         [ 1.6502e+03,  8.9508e+02, -1.0091e+03, -1.1972e+01,  1.5445e+02,
           7.2761e-01],
         [ 1.7281e+03,  7.5338e+02, -9.5853e+02, -1.7052e+01,  1.8006e+02,
           7.5683e-01],
         [ 1.6022e+03,  6.3476e+02, -9.3926e+02,  8.3473e-01,  1.8265e+02,
           6.9264e-01]],

        [[ 2.9419e+03,  1.2845e+03, -8.8098e+02, -5.9183e+01,  1.8027e+02,
           6.1402e-01],
         [ 1.2277e+03,  1.0341e+03, -1.0066e+03, -1.0945e+01,  1.4210e+02,
           7.1758e-01],
         [ 1.5767e+03,  8.9380e+02, -1.0231e+03, -8.4546e+00,  1.4684e+02,
           7.7063e-01],
         [ 1.6566e+03,  7.4822e+02, -9.7399e+02, -2.3077e+01,  1.5460e+02,
           7.4564e-01],
         [ 1.5431e+03,  6.3031e+02, -9.3815e+02,  7.3185e-02,  1.7917e+02,
           7.2534e-01]],

        [[ 2.8879e+03,  1.2790e+03, -8.0928e+02, -8.1971e+01,  1.9779e+02,
           7.2927e-01],
         [ 1.1693e+03,  1.0257e+03, -9.9828e+02,  7.1265e+00,  1.6076e+02,
           6.5228e-01],
         [ 1.5194e+03,  9.0136e+02, -1.0100e+03, -2.3660e+00,  1.7544e+02,
           7.6933e-01],
         [ 1.5903e+03,  7.5392e+02, -9.7073e+02, -1.4556e+01,  1.5973e+02,
           7.7908e-01],
         [ 1.4732e+03,  6.3976e+02, -9.3782e+02,  8.6335e+00,  1.7668e+02,
           7.9308e-01]],

        [[ 2.8132e+03,  1.2710e+03, -1.1207e+03, -1.2051e+02,  2.0229e+02,
           7.8732e-01],
         [ 1.0889e+03,  1.0373e+03, -1.0128e+03,  3.8446e+01,  1.4620e+02,
           2.4946e-01],
         [ 1.4405e+03,  9.0540e+02, -1.0171e+03,  2.8805e+00,  1.7457e+02,
           7.3034e-01],
         [ 1.5344e+03,  7.5954e+02, -9.5824e+02, -4.8594e+00,  1.8395e+02,
           7.5640e-01],
         [ 1.3996e+03,  6.4857e+02, -9.5151e+02,  1.1045e+01,  1.7567e+02,
           6.9732e-01]],

        [[ 2.7407e+03,  1.2608e+03, -1.0877e+03, -1.5226e+02,  1.5719e+02,
           7.5535e-01],
         [ 1.0120e+03,  1.0419e+03, -1.0269e+03,  1.7481e+01,  1.4442e+02,
           4.7099e-01],
         [ 1.3654e+03,  9.1201e+02, -1.0215e+03,  1.2380e+01,  1.4430e+02,
           7.4407e-01],
         [ 1.4755e+03,  7.6695e+02, -9.4068e+02,  6.1064e+00,  1.9054e+02,
           7.7446e-01],
         [ 1.3400e+03,  6.6391e+02, -9.4428e+02,  2.7229e+01,  1.9480e+02,
           7.3418e-01]],

        [[ 2.6754e+03,  1.2541e+03, -1.0123e+03, -1.7991e+02,  1.5472e+02,
           7.4860e-01],
         [ 9.4641e+02,  1.0600e+03, -1.0305e+03,  3.0455e+01,  1.4403e+02,
           7.5502e-01],
         [ 1.2974e+03,  9.1646e+02, -1.0230e+03,  2.0253e+01,  1.3894e+02,
           7.4947e-01],
         [ 1.3961e+03,  7.7817e+02, -9.6610e+02,  1.6486e+01,  1.6827e+02,
           7.7964e-01],
         [ 1.2764e+03,  6.5934e+02, -9.4360e+02,  3.2550e+01,  1.8800e+02,
           7.5908e-01]],

        [[ 2.6181e+03,  1.2522e+03, -1.0110e+03, -1.7632e+02,  1.9465e+02,
           7.8866e-01],
         [ 8.9127e+02,  1.0898e+03, -1.0161e+03,  7.5287e+01,  1.7293e+02,
           7.4819e-01],
         [ 1.2356e+03,  9.2515e+02, -1.0204e+03,  2.9247e+01,  1.6523e+02,
           6.9491e-01],
         [ 1.3243e+03,  7.8018e+02, -9.8233e+02,  2.6656e+01,  1.6148e+02,
           7.3078e-01],
         [ 1.2110e+03,  6.6800e+02, -9.5542e+02,  4.5345e+01,  2.1007e+02,
           7.2692e-01]],

        [[ 2.5518e+03,  1.2453e+03, -1.0105e+03, -1.8239e+02,  2.1644e+02,
           7.7617e-01],
         [ 8.2210e+02,  1.1166e+03, -1.0124e+03,  1.0989e+02,  2.0392e+02,
           7.5404e-01],
         [ 1.1671e+03,  9.3384e+02, -1.0228e+03,  4.5672e+01,  1.9692e+02,
           6.9466e-01],
         [ 1.2728e+03,  7.8484e+02, -9.6550e+02,  3.8717e+01,  1.7440e+02,
           7.8772e-01],
         [ 1.1392e+03,  6.7333e+02, -9.6634e+02,  4.9302e+01,  1.9387e+02,
           7.3821e-01]],

        [[ 2.4863e+03,  1.2385e+03, -1.0046e+03, -1.7627e+02,  1.8820e+02,
           7.6064e-01],
         [ 7.5815e+02,  1.1269e+03, -1.0117e+03,  1.0767e+02,  2.0694e+02,
           7.2307e-01],
         [ 1.0921e+03,  9.4004e+02, -1.0217e+03,  5.7832e+01,  1.6118e+02,
           7.5443e-01],
         [ 1.2098e+03,  7.8963e+02, -9.5213e+02,  4.9536e+01,  2.0187e+02,
           7.5173e-01],
         [ 1.0733e+03,  6.7339e+02, -9.6727e+02,  4.9538e+01,  1.8182e+02,
           7.4694e-01]],

        [[ 2.4157e+03,  1.2347e+03, -1.0057e+03, -1.4614e+02,  1.4150e+02,
           7.4019e-01],
         [ 6.6077e+02,  1.1154e+03, -1.0484e+03,  7.9146e+01,  1.5297e+02,
           5.5725e-01],
         [ 1.0208e+03,  9.5139e+02, -1.0298e+03,  6.7172e+01,  1.6884e+02,
           7.4320e-01],
         [ 1.1314e+03,  7.9700e+02, -9.7342e+02,  5.3145e+01,  1.7029e+02,
           7.6096e-01],
         [ 1.0087e+03,  6.8738e+02, -9.6667e+02,  6.6141e+01,  1.9654e+02,
           7.1958e-01]],

        [[ 2.3675e+03,  1.2334e+03, -9.7957e+02, -1.1575e+02,  1.4731e+02,
           7.2600e-01],
         [ 6.0378e+02,  1.1203e+03, -1.0325e+03,  9.5978e+01,  1.5156e+02,
           6.6110e-01],
         [ 9.3921e+02,  9.7004e+02, -1.0434e+03,  8.2999e+01,  1.6310e+02,